version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 4
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 4
- package-ecosystem: "npm"
  directory: "/test-projects/vite-project/"
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 4
