name: main
on:
  push:
    branches:
    - "*"
  pull_request:
    branches: ["main"]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Use Node.js 20.17.0
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20.17.0
        cache: 'npm'
    - run: ./go.sh
