name: main
on:
  push:
    branches:
    - "*"
  pull_request:
    branches: ["main"]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'npm'
    - run: ./go.sh
